#ifndef __IOCTL_CODE_H__
#define __IOCTL_CODE_H__

#define IOCTL_ON_BEEP \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4001, METHOD_BUFFERED, FILE_ANY_ACCESS)
    
#define IOCTL_OFF_BEEP \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4002, METHOD_BUFFERED, FILE_ANY_ACCESS)


#endif

